<?php
    /** @var Oggetto\Simple\ViewModel\SimpleArray $viewModel */
    $viewModel = $block->getViewModel();
?>

<a href="<?= $block->escapeUrl($block->getCustomUrl()) ?>">Go to google</a>

<select name="some_select">
    <?php foreach ($viewModel->getArray() as $option => $label): ?>
        <option value="<?= $block->escapeHtmlAttr($option) ?>"><?= $label ?></option>
    <?php endforeach; ?>
</select>